# implementation of linear regression model on housing price prediction 

In [71]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns


In [72]:
df = pd.read_csv(r"D:\advanced_training_AIML\Advanced-Training-AIML-Python-\Day-7\House_price_prediction_data.csv")

In [73]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [74]:
df['MiscFeature'].unique()


array([nan, 'Shed', 'Gar2', 'Othr', 'TenC'], dtype=object)

In [75]:
df['Fence'].unique()


array([nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw'], dtype=object)

In [76]:
df['PoolQC'].unique()


array([nan, 'Ex', 'Fa', 'Gd'], dtype=object)

In [77]:
df['Alley'].unique()


array([nan, 'Grvl', 'Pave'], dtype=object)

In [78]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [79]:
df.isnull().sum()[['LotFrontage','Alley','PoolQC','Fence','MiscFeature']]


LotFrontage     259
Alley          1369
PoolQC         1453
Fence          1179
MiscFeature    1406
dtype: int64

In [80]:
df.shape

(1460, 81)

In [81]:
print(df.shape)
df = df.drop(['LotFrontage', 'Alley', 'PoolQC', 'Fence', 'MiscFeature','MSZoning','Street','LotShape','LandContour','Utilities','SaleType'], axis=1)
print(df.shape)


(1460, 81)
(1460, 70)


In [84]:
df.shape

(1460, 70)

In [85]:
df.head()

Id  MSSubClass  LotArea LotConfig LandSlope Neighborhood Condition1  \
0   1          60     8450    Inside       Gtl      CollgCr       Norm   
1   2          20     9600       FR2       Gtl      Veenker      Feedr   
2   3          60    11250    Inside       Gtl      CollgCr       Norm   
3   4          70     9550    Corner       Gtl      Crawfor       Norm   
4   5          60    14260       FR2       Gtl      NoRidge       Norm   

  Condition2 BldgType HouseStyle  ...  OpenPorchSF  EnclosedPorch  3SsnPorch  \
0       Norm     1Fam     2Story  ...           61              0          0   
1       Norm     1Fam     1Story  ...            0              0          0   
2       Norm     1Fam     2Story  ...           42              0          0   
3       Norm     1Fam     2Story  ...           35            272          0   
4       Norm     1Fam     2Story  ...           84              0          0   

   ScreenPorch PoolArea MiscVal MoSold YrSold SaleCondition  SalePrice  
0            0        0       0      2   2008        Normal     208500  
1            0        0       0      5   2007        Normal     181500  
2            0        0       0      9   2008        Normal     223500  
3            0        0       0      2   2006       Abnorml     140000  
4            0        0       0     12   2008        Normal     250000  

[5 rows x 70 columns]

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


In [87]:
x = df.drop('SalePrice', axis=1)
y = df['SalePrice']


In [88]:
x.head()

Id  MSSubClass  LotArea LotConfig LandSlope Neighborhood Condition1  \
0   1          60     8450    Inside       Gtl      CollgCr       Norm   
1   2          20     9600       FR2       Gtl      Veenker      Feedr   
2   3          60    11250    Inside       Gtl      CollgCr       Norm   
3   4          70     9550    Corner       Gtl      Crawfor       Norm   
4   5          60    14260       FR2       Gtl      NoRidge       Norm   

  Condition2 BldgType HouseStyle  ...  WoodDeckSF  OpenPorchSF  EnclosedPorch  \
0       Norm     1Fam     2Story  ...           0           61              0   
1       Norm     1Fam     1Story  ...         298            0              0   
2       Norm     1Fam     2Story  ...           0           42              0   
3       Norm     1Fam     2Story  ...           0           35            272   
4       Norm     1Fam     2Story  ...         192           84              0   

   3SsnPorch ScreenPorch PoolArea MiscVal MoSold YrSold  SaleCondition  
0          0           0        0       0      2   2008         Normal  
1          0           0        0       0      5   2007         Normal  
2          0           0        0       0      9   2008         Normal  
3          0           0        0       0      2   2006        Abnorml  
4          0           0        0       0     12   2008         Normal  

[5 rows x 69 columns]

In [89]:
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64